#!/bin/bash
set -e

# ============================================================
# Beit Midrash Finance — One-Command Setup
# Usage: bash scripts/setup.sh
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║   ניהול כספים - בית המדרש                ║"
echo "║   Beit Midrash Finance — Setup           ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ─── Check Docker ─────────────────────────────────────────────
if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker is not installed."
    echo "Install Docker: https://docs.docker.com/get-docker/"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo "ERROR: Docker Compose is not available."
    echo "Make sure you have Docker Compose v2 (included in Docker Desktop)."
    exit 1
fi

# ─── Check if already set up ─────────────────────────────────
if [ -f .env ]; then
    echo "Found existing .env file."
    read -p "Re-run setup? This will NOT delete your data. [y/N] " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Starting services..."
        docker compose up -d --build
        echo ""
        echo "✓ App is running at http://localhost:3000"
        exit 0
    fi
fi

# ─── Generate secrets ────────────────────────────────────────
echo "Generating secrets..."

POSTGRES_PASSWORD=$(openssl rand -hex 24)
JWT_SECRET=$(openssl rand -hex 32)

# Generate JWTs using Node.js (no extra dependencies needed)
generate_jwt() {
    local role=$1
    local secret=$2
    node -e "
const crypto = require('crypto');

function base64url(str) {
    return Buffer.from(str).toString('base64')
        .replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
}

const header = base64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
const now = Math.floor(Date.now() / 1000);
const payload = base64url(JSON.stringify({
    role: '$role',
    iss: 'supabase',
    iat: now,
    exp: now + (10 * 365 * 24 * 60 * 60) // 10 years
}));

const signature = crypto
    .createHmac('sha256', '$secret')
    .update(header + '.' + payload)
    .digest('base64')
    .replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');

process.stdout.write(header + '.' + payload + '.' + signature);
"
}

ANON_KEY=$(generate_jwt "anon" "$JWT_SECRET")
SERVICE_ROLE_KEY=$(generate_jwt "service_role" "$JWT_SECRET")

# ─── Write .env ───────────────────────────────────────────────
cat > .env << EOF
# Auto-generated by setup.sh — $(date -u +"%Y-%m-%d %H:%M UTC")
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
ANON_KEY=$ANON_KEY
SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
NEXT_PUBLIC_SUPABASE_URL=http://gateway:8000
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
EOF

echo "✓ Generated .env with secrets"

# ─── Start services ───────────────────────────────────────────
echo "Building and starting services (this may take a few minutes on first run)..."
docker compose up -d --build

# ─── Wait for PostgreSQL ──────────────────────────────────────
echo "Waiting for database..."
for i in {1..30}; do
    if docker compose exec -T postgres pg_isready -U postgres -d beit_midrash &> /dev/null; then
        break
    fi
    sleep 2
done

# ─── Create admin user ───────────────────────────────────────
echo "Creating admin user..."

# Generate password hash (PBKDF2-SHA512, 10000 iterations) matching lib/auth.ts
ADMIN_HASH=$(node -e "
const crypto = require('crypto');
const salt = crypto.randomBytes(16).toString('hex');
const hash = crypto.pbkdf2Sync('admin123', salt, 10000, 64, 'sha512').toString('hex');
process.stdout.write(salt + ':' + hash);
")

docker compose exec -T postgres psql -U postgres -d beit_midrash -c \
    "INSERT INTO users (username, password_hash, display_name) VALUES ('admin', '$ADMIN_HASH', 'מנהל / Admin') ON CONFLICT (username) DO NOTHING;"

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║   ✓ Setup complete!                      ║"
echo "║                                          ║"
echo "║   Open: http://localhost:3000             ║"
echo "║   Login: admin / admin123                 ║"
echo "║                                          ║"
echo "║   Change the password after first login!  ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "Useful commands:"
echo "  docker compose logs -f app    # View app logs"
echo "  docker compose stop           # Stop all services"
echo "  docker compose start          # Start all services"
echo "  bash scripts/update.sh        # Pull updates & rebuild"
echo "  bash scripts/backup.sh        # Backup database"
echo ""
